version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - dsgnr
  assignees:
  - dsgnr
  ignore:
  - dependency-name: github-pages
    versions:
    - "211"
    - "212"
    - "213"
  - dependency-name: nokogiri
    versions:
    - 1.11.1
